
import NavBar from "@/components/admin/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";
import SideMenu from "@/components/admin/SideMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`flex flex-col w-full h-screen ${inter.className}`}>
        <NavBar className="block" />
        <div className="flex w-full h-full">
          <SideMenu  />
          <div className="flex-grow bg-backgroundPrimary">{children}</div>
        </div>
      </body>
    </html>
  );
}
