// "use client";

import NavBar from "@/components/admin/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";
import SideMenu from "@/components/admin/SideMenu";
// import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const [sideMenuOpen, setSideMenuOpen] = useState(false);

  // const handleSideMenuOpen = (value) => {
  //   setSideMenuOpen(value);
  // };

  return (
    <html lang="en">
      <body className={`flex flex-col w-full h-screen ${inter.className}`}>
        <NavBar className="block" onSideMenuOpen={handleSideMenuOpen} />
        <div className="flex w-full h-full">
          <SideMenu sideMenuOpenProp={sideMenuOpen} />
          <div className="flex-grow bg-backgroundPrimary">{children}</div>
        </div>
      </body>
    </html>
  );
}
